sudo: required
srevices:
    - docker

scripts:
    - docker build -t lexnim/node .
    - docker images lexnim/node

before-deploy:
    - docker login -u lexnim -p

deploy:
    provider: script
    script: docker push lexnim/node
    on:
        branch: master
